import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { fetchDailySummary } from '../lib/api';
import { CachedSummary, loadCachedSummary, loadDailyLog, saveCachedSummary, todayKey } from '../lib/dailyLog';
import { Theme } from '../theme';
import { Tag } from './ui';

interface Props { visible: boolean; theme: Theme; onClose: () => void }

export function DailySummaryModal({ visible, theme, onClose }: Props) {
  const [cached, setCached] = useState<CachedSummary | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (visible) { setError(null); loadCachedSummary().then(setCached); }
  }, [visible]);

  const request = async (force: boolean) => {
    if (loading) return;
    setLoading(true);
    setError(null);
    const r = await fetchDailySummary(await loadDailyLog(), force);
    setLoading(false);
    if (r.ok) {
      const c = { summary: r.summary, cached: r.cached };
      setCached(c);
      saveCachedSummary(c);
    } else {
      setError(r.message);
    }
  };

  const dim = { color: theme.dim, fontSize: 13 } as const;
  const summary = cached?.summary;
  const highlights = Array.isArray(summary?.highlights) ? summary!.highlights!.filter(Boolean) : [];

  return (
    <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}>
      <View style={{ flex: 1, backgroundColor: theme.bg, paddingTop: 16 }}>
        <View style={s.head}>
          <View>
            <Text style={[s.title, { color: theme.accent }]}>Today's AI Summary</Text>
            <Text style={dim}>{todayKey()}</Text>
          </View>
          <Pressable onPress={onClose} hitSlop={12}><Text style={{ color: theme.accent, fontSize: 16, fontWeight: '600' }}>Done</Text></Pressable>
        </View>
        <ScrollView contentContainerStyle={{ padding: 16 }}>
          <View style={[s.box, { borderColor: theme.border, backgroundColor: theme.card }]}>
            <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 8 }}>
              <Text style={[s.sec, { color: theme.accent }]}>TODAY'S TRAFFIC</Text>
              <Tag text="AI" color={theme.accent} />
            </View>
            {loading ? (
              <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                <ActivityIndicator color={theme.accent} size="small" />
                <Text style={[dim, { marginLeft: 8 }]}>Asking Gemini…</Text>
              </View>
            ) : error ? (
              <>
                <Text style={dim}>{error}</Text>
                <Btn label="Try again" theme={theme} onPress={() => request(true)} />
              </>
            ) : !summary ? (
              <>
                <Text style={dim}>Ask Gemini for a recap of today's notable (military/alert) traffic.</Text>
                <Btn label="Generate summary" theme={theme} onPress={() => request(false)} />
              </>
            ) : (
              <>
                {summary.headline ? <Text style={{ color: theme.text, fontSize: 17, fontWeight: '700' }}>{summary.headline}</Text> : null}
                {summary.summary ? <Text style={{ color: theme.text, fontSize: 14, lineHeight: 20, marginTop: 6 }}>{summary.summary}</Text> : null}
                {highlights.map((h, i) => (
                  <Text key={i} style={{ color: theme.text, fontSize: 14, lineHeight: 20, marginTop: 4 }}>• {h}</Text>
                ))}
                <Btn label="Refresh" theme={theme} onPress={() => request(true)} />
                <Text style={[dim, { marginTop: 10, fontSize: 12 }]}>
                  {cached?.cached === false ? 'AI-generated by Gemini, so double-check anything important.' : 'Cached earlier today · AI-generated by Gemini.'}
                </Text>
              </>
            )}
          </View>
        </ScrollView>
      </View>
    </Modal>
  );
}

function Btn({ label, theme, onPress }: { label: string; theme: Theme; onPress: () => void }) {
  return (
    <Pressable onPress={onPress} style={[s.btn, { borderColor: theme.accent }]}>
      <Text style={{ color: theme.accent, fontWeight: '600', fontSize: 13 }}>{label}</Text>
    </Pressable>
  );
}

const s = StyleSheet.create({
  head: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingBottom: 4 },
  title: { fontSize: 22, fontWeight: '800' },
  box: { borderWidth: 1, borderRadius: 12, padding: 14 },
  sec: { fontSize: 10, letterSpacing: 1.2, fontWeight: '700' },
  btn: { alignSelf: 'flex-start', borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 6, marginTop: 10 },
});
